---
include:
  - project: nci-gdc/gitlab-templates
#    ref: main
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

variables:
  BUILD_PY_VERSION: python3.9
  RELEASE_PY_VERSION: python3.9

default:
  image: docker.osdc.io/ncigdc/python3.9-builder:latest
