---
include:
  - project: nci-gdc/gitlab-templates
    ref: feat/GDCPE-1498-global-updates
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

variables:
  BUILD_PY_VERSION: python3.9
  RELEASE_PY_VERSION: python3.9
