services: docker
git:
  depth: false
install: make docker-login build-docker
stages:
- name: test
- name: publish-docker
jobs:
  include:
  - stage: test
    name: Publish docker image
    script:
    - make run-docker
  - stage: publish
    name: Publish docker image
    script:
    - make docker-login publish-docker
env:
  global:
  - secure: rp0un5bmzGYqkNNiDwLHnIdoXNBbVoDT/DO95ur2JiJzKDlJh51oAI2gyb4c2anxISddMPviKX32CrIKFBS9MCUD6LfUmuaMHy9XVBOfQYb7VoUPfPjWe8eUk54NC5AlrU3mwscYkB1VW9ODp0GpLlfmvStFVp8/g/5JJbCZ35HrTOTH/mg1oXTfB3+tMxrYTtQtFt15JMvT1JM67Xy8GwHpU42QPHNaCMYDVJjLS8bp9n+VFue5/Qc1NRczBD4FfhnEeM/eskcm+JaOFY4eZhdSh9ZkK+Dc3PLXL3IqFTphbvKvRHFKnD8wqbNLzXb1Ja5h2OzGe95g1F3g7Oj2kSdK79beDmReiLNIRtFiaNKFQorZTgoybmxZqRCLPFkxE/eUykIgso8Og3/ieIlYzFzZMPzxPhV77W6SToqSjFFtPRi8NEZS2/FUjFa4MsgTzTFk4e48E/PHIKFWSKMLnTCFThGTrQUzvd324AnTkySNGlqlFL+HM7M5PdctjptNoSDk4iLILRlLpeuSoElKIGujfvsCNT6iVFW/khQMzRwYoCmvtB/QTrroq8Apom+gr90RAySwjK4GAmohPc2XunWJhKyuJBwQxQuSQDxwJ4sOKn/OVj4uy0dlm81LJormoLzgFaM2i96NlyuuFJWdQh+B0kp3DR3roPWCqwk9KeU=
  - secure: B70d8HOnKvGDszqsFFg5qDdUjTMrJESkjtND6G9v9QBRRt/qsy7Kcsx7Uq3rCapP1Z/3TLOlrTS9leYrpuOA7h30w+pJKabd6bsYYer+yh0UDSL1fCCpw3neXeily4Rs60D/bOfXe1U2ZZy/8D7MNSR+QXvqq5Tin5mc02QfaG4zJDxFM2Rkd0uEPryQ3Z8oJ+Hy0TjyjTPueVaLPddZPUijbYzz6i/WiJbzuECQVNv6PyLJO3LLk4kcQAAUrlRC7SpOVu+l3cxGSCwbUTbrHExvVAq0cLXCqS+BaZsj8wnPJk9cJSq/jzl/NqyevSajabdO22OkgFsvL1n7nhDTD/5bOuFvzcXCl0HQMNpDUVL+S+LbEh1TOhrJgF34jcXasyl4cnGqevbgTf4D0qWVXZeyXZ1jdqiVggF3YmhDZwAmSwEfAxpPXoUe+uJUErPzhuNoUwjyEnSJ0GAOSa2j6PxyAZF0EPHVP/fSpxcWDYhPLvbbtR2ry0Hogokq1i1T/t+GioN6XPwG+uRaR2FU14lBZcZZUTe2uNB6vVV87XfrmPkzg86RZmptP343fP5Ak8tj2cMWsQ8cH0eJM6h0FoJOAWPStNUJ2Tk5A/kgZBpO2dr3DfDgWL39/O/UOiWBwXEwhxlJY2TXsqw9WiwMqeLy67AX2nHVfOYTE5xX9vQ=
